### ISSUE TITLE
Please add tags

### ISSUE THREAD

**Issue by scarabeusiv** [awsteiner/o2sclpy#1]
As there are releases on pypi it might help others to find out what changed if they encounter bugs.

**Comment by awsteiner** [comment]
Thank you for your comment. The mainfest.in file seems easy enough (see next commit), but I'm confused about the tags. I looked at https://packaging.python.org/guides/distributing-packages-using-setuptools/ and https://packaging.python.org/tutorials/packaging-projects/ and I don't see anything about tags. Would you mind giving more detail and/or an example?

**Comment by awsteiner** [comment]
Now thinking about it I guess you maybe meant tags on github, so I've put a few up and will keep adding them on the release schedule.

**Comment by scarabeusiv** [comment]
Exactly, sorry I didn't reply sooner. Just git tags so later when we encounter an issue when shipping the package we can use git to show us diff between versions and pinpoint where and when something borked for us :)
